### ISSUE TITLE
message_manager.py - Filtrar mensagens em range_clients ao invés de dispatch_messages.

### ISSUE THREAD

**Issue by AlexPHorta** [vidigal/mobirc#1]
Bom, Victor, considerando que Python é uma linguagem meio liberal quando se trata de manipulação de atributos, será que não seria melhor passar a chamada de ast.literal_eval no começo do método dispatch_messages para o final do método range_clients?

Algo assim:

def range_clients(self):
        if self.sock.clients:
            receive_ready, send_ready, except_ready = select.select(self.get_client_sockets(), [], [], 0.01)
            # Receber mensagens
            for client in receive_ready:
                print('incluindo')
                self.messages.append(**ast.literal_eval(client.recv(512).decode())**)

Desse modo o atributo messages fica limpo logo de cara. Do jeito que está, uma string maléfica pode ficar boiando nessa lista por tempo suficiente para fazer um estrago. Ou eu estou enganado?

PS: Ainda não clonei o repositório, por isso tô colando código aqui... (cuidando da minha filhinha bebê!)

**Comment by vidigal** [comment]
@AlexPHorta parece fazer todo sentido.
Mas queria discutir antes com o pessoal se vamos armazenar as mensagens em formato de dicionário ou se vamos optar por outra forma.
